### ISSUE TITLE
conversation is not stable for Facebook

### ISSUE THREAD

**Issue by hoangphhut** [rampatra/jbot#100]
Hi
I tried Facebook jbot-example with conversation and it works well. Once I add another conversation, it raises an exception at function startConversation(). Then I try to delete all the conversation-related methods in example (but keep mine), then it work. However, after awhile, startConversation() raises exception again as below. It's seem that Anotation in conversation has something wrong. Anybody can have any suggestion please?

Thanks
-------------------
2018-06-07 18:22:35.615 ERROR 4047 --- [nio-8080-exec-7] me.ramswaroop.jbot.core.facebook.Bot     : Error invoking controller: 

java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_171]
	at me.ramswaroop.jbot.core.facebook.Bot.invokeMethods(Bot.java:298) [jbot-4.0.2-SNAPSHOT.jar:4.0.2-SNAPSHOT]
	at me.ramswaroop.jbot.core.facebook.Bot.setupWebhookEndpoint(Bot.java:145) [jbot-4.0.2-SNAPSHOT.jar:4.0.2-SNAPSHOT]
	at sun.reflect.GeneratedMethodAccessor92.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_171]

.......
 Caused by: java.lang.StackOverflowError: null
	at me.ramswaroop.jbot.core.common.BaseBot.formConversationQueue(BaseBot.java:154) ~[jbot-4.0.2-SNAPSHOT.jar:4.0.2-SNAPSHOT]
	at me.ramswaroop.jbot.core.common.BaseBot.formConversationQueue(BaseBot.java:154) ~[jbot-4.0.2-SNAPSHOT.jar:4.0.2-SNAPSHOT]
	at me.ramswaroop.jbot.core.common.BaseBot.formConversationQueue(BaseBot.java:154) ~[jbot-4.0.2-SNAPSHOT.jar:4.0.2-SNAPSHOT]
	at me.ramswaroop.jbot.core.common.BaseBot.formConversationQueue(BaseBot.java:154) ~[jbot-4.0.2-SNAPSHOT.jar:4.0.2-SNAPSHOT]
	at me.ramswaroop.jbot.core.common.BaseBot.formConversationQueue(BaseBot.java:154) ~[jbot-4.0.2-SNAPSHOT.jar:4.0.2-SNAPSHOT]
	at me.ramswaroop.jbot.core.common.BaseBot.formConversationQueue(BaseBot.java:154) ~[jbot-4.0.2-SNAPSHOT.jar:4.0.2-SNAPSHOT]
	at me.ramswaroop.jbot.core.common.BaseBot.formConversationQueue(BaseBot.java:154) ~[jbot-4.0.2-SNAPSHOT.jar:4.0.2-SNAPSHOT]
	at me.ramswaroop.jbot.core.common.BaseBot.formConversationQueue(BaseBot.java:154) ~[jbot-4.0.2-SNAPSHOT.jar:4.0.2-SNAPSHOT]
	at me.ramswaroop.jbot.core.common.BaseBot.formConversationQueue(BaseBot.java:154) ~[jbot-4.0.2-SNAPSHOT.jar:4.0.2-SNAPSHOT]
	at me.ramswaroop.jbot.core.common.BaseBot.formConversationQueue(BaseBot.java:154) ~[jbot-4.0.2-SNAPSHOT.jar:4.0.2-SNAPSHOT]
	at me.ramswaroop.jbot.core.common.BaseBot.formConversationQueue(BaseBot.java:154) ~[jbot-4.0.2-SNAPSHOT.jar:4.0.2-SNAPSHOT]
	at me.ramswaroop.jbot.core.common.BaseBot.formConversationQueue(BaseBot.java:154) ~[jbot-4.0.2-SNAPSHOT.jar:4.0.2-SNAPSHOT]
	at me.ramswaroop.jbot.core.common.BaseBot.formConversationQueue(BaseBot.java:154) ~[jbot-4.0.2-SNAPSHOT.jar:4.0.2-SNAPSHOT]
	at me.ramswaroop.jbot.core.common.BaseBot.formConversationQueue(BaseBot.java:154) ~[jbot-4.0.2-SNAPSHOT.jar:4.0.2-SNAPSHOT]
	at me.ramswaroop.jbot.core.common.BaseBot.formConversationQueue(BaseBot.java:154) ~[jbot-4.0.2-SNAPSHOT.jar:4.0.2-SNAPSHOT]
	at me.ramswaroop.jbot.core.common.BaseBot.formConversationQueue(BaseBot.java:154) ~[jbot-4.0.2-SNAPSHOT.jar:4.0.2-SNAPSHOT]
	at me.ramswaroop.jbot.core.common.BaseBot.formConversationQueue(BaseBot.java:154) ~[jbot-4.0.2-SNAPSHOT.jar:4.0.2-SNAPSHOT]
	at me.ramswaroop.jbot.core.common.BaseBot.formConversationQueue(BaseBot.java:154) ~[jbot-4.0.2-SNAPSHOT.jar:4.0.2-SNAPSHOT]
	at me.ramswaroop.jbot.core.common.BaseBot.formConversationQueue(BaseBot.java:154) ~[jbot-4.0.2-SNAPSHOT.jar:4.0.2-SNAPSHOT]
	at me.ramswaroop.jbot.core.common.BaseBot.formConversationQueue(BaseBot.java:154) ~[jbot-4.0.2-SNAPSHOT.jar:4.0.2-SNAPSHOT]
	at me.ramswaroop.jbot.core.common.BaseBot.formConversationQueue(BaseBot.java:154) ~[jbot-4.0.2-SNAPSHOT.jar:4.0.2-SNAPSHOT]
	at me.ramswaroop.jbot.core.common.BaseBot.formConversationQueue(BaseBot.java:154) ~[jbot-4.0.2-SNAPSHOT.jar:4.0.2-SNAPSHOT]
	at me.ramswaroop.jbot.core.common.BaseBot.formConversationQueue(BaseBot.java:154) ~[jbot-4.0.2-SNAPSHOT.jar:4.0.2-SNAPSHOT]
	at me.ramswaroop.jbot.core.common.BaseBot.formConversationQueue(BaseBot.java:154) ~[jbot-4.0.2-SNAPSHOT.jar:4.0.2-SNAPSHOT]
	at me.ramswaroop.jbot.core.common.BaseBot.formConversationQueue(BaseBot.java:154) ~[jbot-4.0.2-SNAPSHOT.jar:4.0.2-SNAPSHOT]
	at me.ramswaroop.jbot.core.common.BaseBot.formConversationQueue(BaseBot.java:154) ~[jbot-4.0.2-SNAPSHOT.jar:4.0.2-SNAPSHOT]
	at me.ramswaroop.jbot.core.common.BaseBot.formConversationQueue(BaseBot.java:154) ~[jbot-4.0.2-SNAPSHOT.jar:4.0.2-SNAPSHOT]
	at me.ramswaroop.jbot.core.common.BaseBot.formConversationQueue(BaseBot.java:154) ~[jbot-4.0.2-SNAPSHOT.jar:4.0.2-SNAPSHOT]
	at me.ramswaroop.jbot.core.common.BaseBot.formConversationQueue(BaseBot.java:154) ~[jbot-4.0.2-SNAPSHOT.jar:4.0.2-SNAPSHOT]
	at me.ramswaroop.jbot.core.common.BaseBot.formConversationQueue(BaseBot.java:154) ~[jbot-4.0.2-SNAPSHOT.jar:4.0.2-SNAPSHOT]

**Comment by hoangphhut** [comment]
I found my problem, it's because of "loop conversation".
By the way, is there any way to support loop conversation, such like below:
1. start conversation
2. do something and send to user
3. check user's response, if yes, come back 2. If no, go to 4.
4. stop conversation

**Comment by rampatra** [comment]
Hi @hoangphhut, yes this is one of the limitations in the current version of JBot. Currently, conversations are backed by a `List` data structure which needs to be replaced with a graph probably to support going back and forth. Having said that, I am unfortunately not free for the next 6 months to contribute to this epic. I am closing this issue for now.

**Comment by hoangphhut** [comment]
Thanks @rampatra for your prompt reply. I see that once JBot got exception (such as with my loop conversation), it work not stable even I had corrected the code. For example, it receive call back from Fb and do nothing, as following log. Can you have any sugession? What should I do? 

2018-06-09 01:35:17.604 DEBUG 2954 --- [nio-8080-exec-2] me.ramswaroop.jbot.core.facebook.Bot     : Callback from fb: {"object":"page","entry":[{"id":"467789410318097","time":1528482917369,"messaging":[{"sender":{"id":"1690175874370007"},"recipient":{"id":"467789410318097"},"timestamp":1528482916626,"message":{"mid":"mid.$cAAHzh-Ji3mhqEfOxElj4K5DTN_wz","seq":572976,"text":"menu"}}]}]}
2018-06-09 01:37:47.263 DEBUG 2954 --- [nio-8080-exec-3] me.ramswaroop.jbot.core.facebook.Bot     : Callback from fb: {"object":"page","entry":[{"id":"467789410318097","time":1528483065989,"messaging":[{"sender":{"id":"1690175874370007"},"recipient":{"id":"467789410318097"},"timestamp":1528483065476,"message":{"mid":"mid.$cAAHzh-Ji3mhqEfX2hFj4LCIvKHRd","seq":572977,"text":"alo"}}]}]}
2018-06-09 01:42:27.252 DEBUG 2954 --- [nio-8080-exec-8] me.ramswaroop.jbot.core.facebook.Bot     : Callback from fb: {"object":"page","entry":[{"id":"467789410318097","time":1528483347040,"messaging":[{"sender":{"id":"1690175874370007"},"recipient":{"id":"467789410318097"},"timestamp":1528483346343,"message":{"mid":"mid.$cAAHzh-Ji3mhqEfo_p1j4LTSHL_EY","seq":572978,"text":"aloaloalo"}}]}]}
