### ISSUE TITLE
file private URL is null in the event

### ISSUE THREAD

**Issue by human-research** [rampatra/jbot#101]
Hello. 
I have spring boot app that uses jbot 4.0.1 for slack conversations. 
I have a bot that occupied one channel and I interact with the only channel, I'm not calling the bot from another channels. 
In case of messages, the bot works well, my app handles incoming messages and replies to slack. 
When I'm trying to drop the file into the channel, file sends, my app handles the event and trying to extract the file url. 
There was an exception: 

> Caused by: java.lang.NullPointerException: null
>	at java.net.URI$Parser.parse(URI.java:3042) ~[na:1.8.0_161]
>	at java.net.URI.<init>(URI.java:588) ~[na:1.8.0_161]
>	at java.net.URI.create(URI.java:850) ~[na:1.8.0_161]
>	at com.sun.jersey.api.client.Client.resource(Client.java:433) ~[jersey-client-1.8.jar:1.8]
>	at net.bcnnm.notifications.fcc.NotificationServer.fetchFile(NotificationServer.java:255) ~[classes/:na]
>	at net.bcnnm.notifications.fcc.NotificationServer.uploadFile(NotificationServer.java:244) ~[classes/:na]
>	at net.bcnnm.notifications.slack.SlackBot.onUpload(SlackBot.java:85) ~[classes/:na]
>	... 27 common frames omitted

```
    @Controller(events = {EventType.FILE_SHARED})
    public void onUpload(WebSocketSession session, Event event) {
        File file = event.getFile();
        notificationServer.uploadFile(file);

        reply(session, event, new Message("File was sent "));
    }
```

```
    public void uploadFile(File file) {
        try {
            System.out.println("Sending UPLOAD command..");

            byte[] fileBytes = fetchFile(file);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
```

```
private byte[] fetchFile(File file) throws IOException {
        Client client = Client.create();
        WebResource resource = client.resource(file.getUrlPrivate());
        ClientResponse response = resource
                .header("Authorization", String.format("Bearer %s", slackBot.getSlackToken()))
                .get(ClientResponse.class);

        InputStream is = response.getEntity(InputStream.class);

        return IOUtils.toByteArray(is);
    }
```

Debug info:

```
this = {SlackBot@6303} 
 token = "%removed%"
 defaultChannel = "%removed%"
 defaultSession = {StandardWebSocketSession@6317} "StandardWebSocketSession[id=0, uri=null]"
 askQueue = {ArrayBlockingQueue@6323}  size = 0
 notificationServer = {NotificationServer@6319} 
 slackService = {SlackService@6324} 
 eventToMethodsMap = {HashMap@6325}  size = 2
 methodNameMap = {HashMap@6326}  size = 2
 conversationMethodNames = {ArrayList@6327}  size = 0
 conversationQueueMap = {HashMap@6328}  size = 0
session = {StandardWebSocketSession@6317} "StandardWebSocketSession[id=0, uri=null]"
event = {Event@6318} 
 id = 0
 type = "file_shared"
 subtype = null
 botId = null
 channelId = null
 userId = "%removed%"
 text = null
 edited = null
 error = null
 ok = false
 replyTo = 0
 isStarred = false
 pinnedTo = null
 channel = null
 item = null
 bot = null
 file = {File@6342} 
 fileId = "FB4E52TD5"
 user = null
 hasPins = false
 reactions = null
 upload = false
 hidden = false
 latest = null
 presence = null
 comment = null
 commentId = null
 reaction = null
 itemUser = null
 names = null
 value = null
 plan = null
 url = null
 domain = null
 emailDomain = null
 teamId = null
 subteam = null
 subteamId = null
 dndStatus = null
 ts = null
 threadTs = null
 deletedTs = null
 eventTs = "1528375392.000009"
 message = null
file = {File@6342} 
 id = "FB4E52TD5"
 created = 0
 timestamp = 0
 name = null
 title = null
 mimetype = null
 filetype = null
 prettyType = null
 user = null
 mode = null
 editable = false
 isExternal = false
 externalType = null
 username = null
 size = 0
 urlPrivate = null
 urlPrivateDownload = null
 thumb64 = null
 thumb80 = null
 thumb360 = null
 thumb360Gif = null
 thumb360W = null
 thumb360H = null
 thumb480 = null
 thumb480W = null
 thumb480H = null
 thumb160 = null
 permalink = null
 permalinkPublic = null
 editLink = null
 preview = null
 previewHighlight = null
 lines = 0
 linesMore = 0
 isPublic = false
 publicUrlShared = false
 displayAsBot = false
 channels = null
 groups = null
 ims = null
 initialComment = null
 numStars = 0
 isStarred = false
 pinnedTo = null
 reactions = null
 commentsCount = 0
```

NPE is the result of `client.resource(file.getUrlPrivate())`

**Comment by human-research** [comment]
Everything became clear after reading slack api docs:
https://api.slack.com/events/file_shared 
I should use files.info API method to obtain file's full info.
