### ISSUE TITLE
java.lang.IllegalArgumentException: Sources must not be empty

### ISSUE THREAD

**Issue by Ravi565** [rampatra/jbot#161]
java.lang.IllegalArgumentException: Sources must not be empty
	at org.springframework.util.Assert.notEmpty(Assert.java:464) ~[spring-core-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:391) [spring-boot-2.2.1.BUILD-SNAPSHOT.jar:2.2.1.BUILD-SNAPSHOT]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:314) [spring-boot-2.2.1.BUILD-SNAPSHOT.jar:2.2.1.BUILD-SNAPSHOT]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) [spring-boot-2.2.1.BUILD-SNAPSHOT.jar:2.2.1.BUILD-SNAPSHOT]
	at org.springframework.boot.SpringApplication.main(SpringApplication.java:1242) [spring-boot-2.2.1.BUILD-SNAPSHOT.jar:2.2.1.BUILD-SNAPSHOT

**Comment by Ravi565** [comment]
unable to run spring boot application.
