### ISSUE TITLE
WebSocketConnectionManager     : Failed to connect

### ISSUE THREAD

**Issue by Alunkal** [rampatra/jbot#170]
2020-03-27 10:28:47.875 ERROR 8692 --- [cTaskExecutor-1] o.s.w.s.c.WebSocketConnectionManager     : Failed to connect

javax.websocket.DeploymentException: The HTTP response from the server [404] did not permit the HTTP upgrade to WebSocket
        at org.apache.tomcat.websocket.WsWebSocketContainer.connectToServer(WsWebSocketContainer.java:346) ~[tomcat-embed-websocket-8.5.14.jar:8.5.14]
        at org.springframework.web.socket.client.standard.StandardWebSocketClient$1.call(StandardWebSocketClient.java:150) ~[spring-websocket-4.3.8.RELEASE.jar:4.3.8.RELEASE]
        at org.springframework.web.socket.client.standard.StandardWebSocketClient$1.call(StandardWebSocketClient.java:147) ~[spring-websocket-4.3.8.RELEASE.jar:4.3.8.RELEASE]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:830) ~[na:na]

**Comment by rampatra** [comment]
It's a 404 error so please make sure the URL is correct. Closing as it doesn't seem to be an issue with the library. You can re-open if otherwise.
