### ISSUE TITLE
Websocket session closing

### ISSUE THREAD

**Issue by kjella** [rampatra/jbot#186]
Using version 4.1.2-rc.3-SNAPSHOT I get the following exception after a couple of hours running the bot:
`java.lang.IllegalStateException: Message will not be sent because the WebSocket session has been closed`

Here is the complete stack trace:
`java.lang.IllegalStateException: Message will not be sent because the WebSocket session has been closed
    at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.writeMessagePart(WsRemoteEndpointImplBase.java:424) ~[tomcat-embed-websocket-8.5.4.jar!/:8.5.4]
    at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.sendMessageBlock(WsRemoteEndpointImplBase.java:309) ~[tomcat-embed-websocket-8.5.4.jar!/:8.5.4]
    at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.sendMessageBlock(WsRemoteEndpointImplBase.java:250) ~[tomcat-embed-websocket-8.5.4.jar!/:8.5.4]
    at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.sendPartialString(WsRemoteEndpointImplBase.java:223) ~[tomcat-embed-websocket-8.5.4.jar!/:8.5.4]
    at org.apache.tomcat.websocket.WsRemoteEndpointBasic.sendText(WsRemoteEndpointBasic.java:49) ~[tomcat-embed-websocket-8.5.4.jar!/:8.5.4]
    at org.springframework.web.socket.adapter.standard.StandardWebSocketSession.sendTextMessage(StandardWebSocketSession.java:197) ~[spring-websocket-4.3.2.RELEASE.jar!/:4.3.2.RELEASE]
    at org.springframework.web.socket.adapter.AbstractWebSocketSession.sendMessage(AbstractWebSocketSession.java:104) ~[spring-websocket-4.3.2.RELEASE.jar!/:4.3.2.RELEASE]
    at me.ramswaroop.jbot.core.slack.Bot$PingTask.run(Bot.java:361) ~[jbot-4.1.2-rc.3-SNAPSHOT.jar!/:4.1.2-rc.3-SNAPSHOT]
    at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]
    at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[na:na]
    at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[na:na]
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
    at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]`

**Comment by rampatra** [comment]
Can you please paste the complete stack trace? The above is not complete.

**Comment by kjella** [comment]
Just updated my original issue with all the logging statements regarding the IllegalStateException.

**Comment by kjella** [comment]
@rampatra Do you have enough information?

**Comment by kjella** [comment]
Any update on this?
