### ISSUE TITLE
Getting URI not absolute error while using the jbot-examples

### ISSUE THREAD

**Issue by jivanpuri** [rampatra/jbot#96]
I am getting following error while running the jbot-examples: **mvn spring-boot:run**
I am just using slack profile & provide token in application.properties file but getting this error.

```java
[ERROR] Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:1.4.0.RELEASE:run (default-cli) on project time: An exception occurred while running. null: InvocationTargetException: Error creating bean with name 'slackWebhooks': Invocation of init method failed; nested exception is java.lang.IllegalArgumentException: URI is not absolute -> [Help 1]

Caused by: java.lang.IllegalArgumentException: URI is not absolute
	at java.net.URI.toURL(URI.java:1088)
	at org.springframework.http.client.SimpleClientHttpRequestFactory.createRequest(SimpleClientHttpRequestFactory.java:137)
	at org.springframework.http.client.support.HttpAccessor.createRequest(HttpAccessor.java:77)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:615)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:580)
	at org.springframework.web.client.RestTemplate.postForEntity(RestTemplate.java:407)
	at example.jbot.slack.SlackWebhooks.invokeSlackWebhook(SlackWebhooks.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:365)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:310)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:133)
	... 24 more
```

**Comment by ramswaroop** [comment]
Hi @jivanpuri, can you please fill these below properties or just remove the values:
```properties
slashCommandToken=<paste your slash command token>
slackIncomingWebhookUrl=<paste your slack incoming webhook url>
```

**Comment by jivanpuri** [comment]
Thanks for responding; Removing values does not work & it errors out. For now, I have provided some dummy values & it is working.
**Error when values are removed:**
Error creating bean with name 'slackWebhooks': Injection of autowired dependencies failed; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'slackIncomingWebhookUrl' in string value "${slackIncomingWebhookUrl}"

**Comment by ramswaroop** [comment]
Thanks for the update, will modify the code to check for emptiness. For now, please go ahead with specifying an arbitrary url.
